services:
  postgres:
    container_name: demo-express-postgres
    image: postgres:17-alpine
    restart: unless-stopped
    ports:
      - "20010:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: backend

  redis:
    container_name: demo-express-redis
    image: redis:7-alpine
    command: redis-server --requirepass redispassword
    restart: unless-stopped
    ports:
      - "20011:6379"

  rabbit:
    container_name: demo-express-rabbit
    image: rabbitmq:3-management-alpine
    restart: unless-stopped
    ports:
      - "20012:5672"
      - "20013:15672"
    environment:
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_DEFAULT_PASS: rabbitpassword
